
    bytenum = 1024 * 1024
    sdim buf, bytenum
    repeat bytenum / 2
        val = rnd(32768)
        wpoke buf, cnt*2, val
    loop
    name = strf("a%05d.dat", 0)
    bsave name, buf, bytenum

